export default[
    {
        id:"CS1",
        branch:"CSE",
        semester:"1st",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"CS2",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"IT1",
        branch:"IT",
        semester:"1st",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"IT2",
        branch:"IT",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"AI1",
        branch:"AI",
        semester:"1st",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"AI2",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"ME1",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"ME2",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"EC1",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"EC2",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"EE1",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"EE2",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"CE1",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    {
        id:"CE2",
        branch:"CSE",
        semester:"2nd",
        total_credits:20.5,
        subjects:[
            {
                id:0,
                name:"Maths-I",
                credits:4
            },
            {
                id:1,
                name:"Physics/Chemistry",
                credits:4
            },
            {
                id:2,
                name:"CSK/HV",
                credits:2
            },
            {
                id:3,
                name:"BME/PPS",
                credits:2
            },
            {
                id:4,
                name:"BEE/BCE",
                credits:2
            },
            {
                id:5,
                name:"Physics/Chemistry Lab",
                credits:1
            },
            {
                id:6,
                name:"CSK/HV Lab",
                credits:1
            },
            {
                id:7,
                name:"MPW/PPS Lab",
                credits:1.5
            },
            {
                id:8,
                name:"BEE/BCE Lab",
                credits:1
            },
            {
                id:9,
                name:"CAMD/CAEG",
                credits:1.5
            },
            {
                id:10,
                name:"SODECA",
                credits:0.5
            },

        ]
    },
    
]